// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_o7O-SUBC14dHylZVAqHbNN1wJ0svBw',
    appId: '1:1009273171314:web:0da4135efab67de5f641eb',
    messagingSenderId: '1009273171314',
    projectId: 'wordier-aeb03',
    authDomain: 'wordier-aeb03.firebaseapp.com',
    storageBucket: 'wordier-aeb03.appspot.com',
    measurementId: 'G-ZEJFX3HJR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc_rpHRXacOq_mhEbVuCBpslxX_bpj0NI',
    appId: '1:1009273171314:android:dd0ec40b887f5e6df641eb',
    messagingSenderId: '1009273171314',
    projectId: 'wordier-aeb03',
    storageBucket: 'wordier-aeb03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEYNqs5qRRoyx-uGDRU-81puCjeqk8roc',
    appId: '1:1009273171314:ios:e2d0593b2b3ece72f641eb',
    messagingSenderId: '1009273171314',
    projectId: 'wordier-aeb03',
    storageBucket: 'wordier-aeb03.appspot.com',
    iosClientId: '1009273171314-fcj79tcbrcrm3b9fdkjkgv86iv07gdfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEYNqs5qRRoyx-uGDRU-81puCjeqk8roc',
    appId: '1:1009273171314:ios:e2d0593b2b3ece72f641eb',
    messagingSenderId: '1009273171314',
    projectId: 'wordier-aeb03',
    storageBucket: 'wordier-aeb03.appspot.com',
    iosClientId: '1009273171314-fcj79tcbrcrm3b9fdkjkgv86iv07gdfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordier',
  );
}
